const DeploymentIndex = () => {
    return (
        <div>
            <div className="bgn-second no-code" style={{flexDirection:"column", alignItems:"center", padding:"5%"}}>
                <h1 style={{marginBottom:"5%"}}>Introduccion</h1>
                <p><span style={{color:"red"}}>Disclaimer*</span> Al igual que la seccion de MERN Authentication, esta solamente era una seccion "extra" al contenido base entregado... previamente he aprendido a alojar paginas WEB creadas en Spring con Java en el servicion AWS (es el que enseñan en el bootcamp) aun asi estos mismos conocimientos me han servido para aprender a alojar otros proyectos de distintos lenguajes y poder crear shell scripts para facilitar el despliegue de las aplicaciones. Actualmente los sevicios entre los que he podido alojar mis proyectos se encuentra Amazon Web Service, Google Cloud Plataform, Microsoft Azure y Oracle Cloud</p><br /><br />
                <p><span style={{color:"red"}}>Disclaimer 2*</span> Actualmente esta seccion esta en desarrollo dejando las contenidos mas importantes para el puesto de desarrollador Full-stack, Front-end y Back-end como principal objetivo</p>
                <p>¡Hola! En esta sección de mi portafolio, me complace mostrarles mi experiencia en el despliegue de aplicaciones MERN. Durante esta etapa, he trabajado en diferentes ejercicios que implican la configuración de mi aplicación MERN para poder desplegarla en un servicio cloud, la configuración de una máquina virtual capaz de alojar mi proyecto MERN, la configuración a través del shell de la máquina virtual de las dependencias y servicios que necesita mi aplicación para su buen funcionamiento, la utilización de comandos unix para navegar a través de mi servidor con sistema Ubuntu, la configuración de Vim para realizar configuraciones en mi aplicación, la utilización de Nginx como servidor web y finalmente, la habilidad para mantener mi página web activa sin la necesidad de tener la consola activa.<br/><br/>Una de las cosas más interesantes que aprendí en esta área fue la importancia de tener una buena configuración y planificación antes de desplegar nuestra aplicación en producción. Durante este proceso, aprendí a configurar adecuadamente mi servidor y las dependencias necesarias para que mi aplicación funcionara de manera óptima en producción.<br/><br/>Además, también aprendí a utilizar diferentes herramientas y comandos para navegar y configurar mi servidor de manera eficiente, como la utilización de comandos unix y la configuración de Vim para realizar cambios en mi aplicación.<br/><br/>En resumen, en esta sección de mi portafolio podrán encontrar ejemplos de mi trabajo en el despliegue de aplicaciones MERN, donde podrán apreciar mi habilidad para configurar adecuadamente un servicio cloud, utilizar diferentes herramientas y comandos para configurar mi servidor de manera eficiente y mantener mi página web activa sin la necesidad de tener la consola activa.</p>
            </div>
        </div>
    );
}
 
export default DeploymentIndex;